server:
  port: 9999
spring:
  application:
    name: zuul-proxy


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  routes:
    user-service:
      path: /userService/**
    order-service:
      path: /orderService/**
  prefix: /proxy